const SET_QUERY = 'SET_QUERY';
const ADD_RECORD = 'ADD_RECORD';
const FETCH_REGISTER_PENDING = 'FETCH_PRODUCTS_PENDING';
const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
const FETCH_REGISTER_ERROR = 'FETCH_REGISTER_ERROR';

export default {
    SET_QUERY,
    ADD_RECORD,
    FETCH_REGISTER_PENDING,
    FETCH_REGISTER_SUCCESS,
    FETCH_REGISTER_ERROR,
};
