const SET_QUERY = 'SET_QUERY';
const ADD_RECORD = 'ADD_RECORD';
const FETCH_REGISTER_PENDING = 'FETCH_PRODUCTS_PENDING';
const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
const FETCH_REGISTER_ERROR = 'FETCH_REGISTER_ERROR';
const SAVE_RESULTS_TO_STORE = 'SAVE_RESULTS_TO_STORE';
const CLEAR_ERRORS = 'CLEAR_ERRORS';

export default {
    SET_QUERY,
    ADD_RECORD,
    FETCH_REGISTER_PENDING,
    FETCH_REGISTER_SUCCESS,
    FETCH_REGISTER_ERROR,
    SAVE_RESULTS_TO_STORE,
    CLEAR_ERRORS,
};
